name: klik_makan
description: "Aplikasi Pemesanan Makanan dengan Flutter dan Firebase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # --- Ikon Bawaan iOS ---
  cupertino_icons: ^1.0.8

  # --- 1. FIREBASE (Database & Auth) ---
  firebase_core: ^3.6.0        # Wajib: Inti koneksi Firebase
  firebase_auth: ^5.3.1        # Fitur Login & Register
  cloud_firestore: ^5.4.4      # Database Menu & Pesanan
  firebase_storage: ^12.0.0    # Penyimpanan (Opsional/Jaga-jaga)
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.1
  geocoding: ^2.1.1
  url_launcher: ^6.2.1
  firebase_messaging: ^15.1.0
  


  # --- 2. STATE MANAGEMENT (Pengelola Data) ---
  provider: ^6.1.2             # Untuk mengelola data keranjang (Cart)

  # --- 3. TAMPILAN & FORMATTING ---
  google_fonts: ^6.2.1         # Agar font aplikasi lebih bagus
  intl: ^0.18.1                # Untuk format uang (Rp 15.000)
  cached_network_image: ^3.4.1 # Agar gambar makanan tidak loading terus
  image_picker: ^1.1.2         # Untuk ambil foto bukti transfer
  date_format: ^2.0.7
  pdf: ^3.10.2
  printing: ^5.11.2
  http: ^1.1.0 
  path_provider: ^2.1.3
  permission_handler: ^11.0.0
  open_file: ^3.3.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # --- ALAT GANTI ICON OTOMATIS ---
  flutter_launcher_icons: ^0.13.1

# --- KONFIGURASI ICON APLIKASI ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png" # Pastikan gambarmu ada di folder assets dan namanya logo.png
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Agar gambar di folder assets bisa terbaca
  assets:
    - assets/